#!/bin/sh

set -e

export ATLAS_TOKEN=`cat ~/.vagrant.d/data/vagrant_login_token`
vagrant destroy --force
vagrant up
rm -f devops-jumpstart.box
vagrant push local
vagrant box add --force --name xpeppers/devops-jumpstart devops-jumpstart.box
vagrant push remote
