#!/bin/sh

set -e

vagrant destroy --force
vagrant up
vagrant halt
VBoxManage sharedfolder remove devops-jumpstart --name vagrant
VBoxManage modifyvm devops-jumpstart --clipboard bidirectional
VBoxManage export devops-jumpstart -o devops-jumpstart.ova
